"""Add marca and url_imagem to perfume

Revision ID: 0d9f45d1987a
Revises: 9f869d118482
Create Date: 2026-04-13 14:04:02.432109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9f45d1987a'
down_revision = '9f869d118482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('url_imagem', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfume', schema=None) as batch_op:
        batch_op.drop_column('url_imagem')
        batch_op.drop_column('marca')

    # ### end Alembic commands ###
