"""add_multitenant_sharing_archiving_task_groups

Revision ID: 11d342844fcd
Revises: 1ac508a98bdb
Create Date: 2026-08-29 23:50:44.189666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d342844fcd'
down_revision = '1ac508a98bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'shared_task_groups' not in tables:
        op.create_table('shared_task_groups',
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('grupo_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['grupo_id'], ['grupo_tarefas.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('user_id', 'grupo_id')
        )

    grupo_cols = [c['name'] for c in inspector.get_columns('grupo_tarefas')]
    with op.batch_alter_table('grupo_tarefas', schema=None) as batch_op:
        if 'owner_id' not in grupo_cols:
            batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_grupo_tarefas_owner', 'user', ['owner_id'], ['id'])
        if 'is_active' not in grupo_cols:
            batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # Data migration: Ensure user 'anderson' exists and update existing orphan groups
    user_res = bind.execute(sa.text('SELECT id FROM "user" WHERE username = \'anderson\'')).fetchone()
    if user_res:
        anderson_id = user_res[0]
    else:
        from werkzeug.security import generate_password_hash
        pwd_hash = generate_password_hash("anderson123")
        bind.execute(
            sa.text('INSERT INTO "user" (username, password_hash) VALUES (:u, :p)'),
            {"u": "anderson", "p": pwd_hash}
        )
        user_res = bind.execute(sa.text('SELECT id FROM "user" WHERE username = \'anderson\'')).fetchone()
        anderson_id = user_res[0]

    bind.execute(
        sa.text("UPDATE grupo_tarefas SET owner_id = :aid, is_active = true WHERE owner_id IS NULL"),
        {"aid": anderson_id}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo_tarefas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_active')
        batch_op.drop_column('owner_id')

    op.drop_table('shared_task_groups')
    # ### end Alembic commands ###
