"""add_multitenant_sharing_archiving

Revision ID: 1ac508a98bdb
Revises: 9be9a207b55e
Create Date: 2026-08-29 19:02:23.015755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac508a98bdb'
down_revision = '9be9a207b55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('shared_lists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['lista.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'lista_id')
    )
    op.create_table('shared_simple_lists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['lista.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'lista_id')
    )
    op.create_table('shared_tasks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tarefa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tarefa_id')
    )
    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.create_foreign_key('fk_lista_owner', 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.create_foreign_key('fk_tarefa_owner', 'user', ['owner_id'], ['id'])

    # Data migration: Ensure user 'anderson' exists and update existing orphan records
    bind = op.get_bind()
    user_res = bind.execute(sa.text("SELECT id FROM user WHERE username = 'anderson'")).fetchone()
    if user_res:
        anderson_id = user_res[0]
    else:
        from werkzeug.security import generate_password_hash
        pwd_hash = generate_password_hash("anderson123")
        bind.execute(
            sa.text("INSERT INTO user (username, password_hash) VALUES (:u, :p)"),
            {"u": "anderson", "p": pwd_hash}
        )
        user_res = bind.execute(sa.text("SELECT id FROM user WHERE username = 'anderson'")).fetchone()
        anderson_id = user_res[0]

    bind.execute(
        sa.text("UPDATE tarefa SET owner_id = :aid, is_active = 1 WHERE owner_id IS NULL"),
        {"aid": anderson_id}
    )
    bind.execute(
        sa.text("UPDATE lista SET owner_id = :aid, is_active = 1 WHERE owner_id IS NULL"),
        {"aid": anderson_id}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_active')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_active')
        batch_op.drop_column('owner_id')

    op.drop_table('shared_tasks')
    op.drop_table('shared_simple_lists')
    op.drop_table('shared_lists')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
