"""add snippet tags

Revision ID: 47a90a4cfccf
Revises: 9b5ad10b534e
Create Date: 2026-04-16 11:03:32.607965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a90a4cfccf'
down_revision = '9b5ad10b534e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacao', sa.String(length=50), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('denominacao')
    )
    op.create_table('snippet_tags',
    sa.Column('snippet_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippet.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('snippet_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snippet_tags')
    op.drop_table('tag')
    # ### end Alembic commands ###
