"""Add Pessoas models

Revision ID: 4a39a0f7c3fb
Revises: 0d9f45d1987a
Create Date: 2026-04-13 15:32:25.049217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a39a0f7c3fb'
down_revision = '0d9f45d1987a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('rg_numero', sa.String(length=20), nullable=True),
    sa.Column('rg_orgao', sa.String(length=20), nullable=True),
    sa.Column('rg_data_expedicao', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('pis', sa.String(length=14), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa_arquivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telefone')
    op.drop_table('pessoa_arquivo')
    op.drop_table('endereco')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
