"""initial migration

Revision ID: 5ee2bda1f6bc
Revises: 
Create Date: 2026-03-23 14:47:42.326057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee2bda1f6bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_tarefas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_tarefas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_lista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('grupo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacao', sa.String(length=100), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_lista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_executado', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_tarefas.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status_tarefas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_lista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=150), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_item.id'], ),
    sa.ForeignKeyConstraint(['lista_id'], ['lista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_lista')
    op.drop_table('tarefa')
    op.drop_table('lista')
    op.drop_table('transacao')
    op.drop_table('tipo_lista')
    op.drop_table('status_tarefas')
    op.drop_table('grupo_tarefas')
    op.drop_table('grupo_item')
    # ### end Alembic commands ###
