"""add_multitenant_sharing_archiving_bookmarks

Revision ID: 94fb13dc5041
Revises: 11d342844fcd
Create Date: 2026-08-30 00:02:01.592444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fb13dc5041'
down_revision = '11d342844fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'shared_bookmarks' not in tables:
        op.create_table('shared_bookmarks',
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('bookmark_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['bookmark_id'], ['bookmark.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('user_id', 'bookmark_id')
        )

    bm_cols = [c['name'] for c in inspector.get_columns('bookmark')]
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        if 'owner_id' not in bm_cols:
            batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_bookmark_owner', 'user', ['owner_id'], ['id'])
        if 'is_active' not in bm_cols:
            batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # Data migration: Ensure user 'anderson' exists and update existing orphan bookmarks
    user_res = bind.execute(sa.text('SELECT id FROM "user" WHERE username = \'anderson\'')).fetchone()
    if user_res:
        anderson_id = user_res[0]
    else:
        from werkzeug.security import generate_password_hash
        pwd_hash = generate_password_hash("anderson123")
        bind.execute(
            sa.text('INSERT INTO "user" (username, password_hash) VALUES (:u, :p)'),
            {"u": "anderson", "p": pwd_hash}
        )
        user_res = bind.execute(sa.text('SELECT id FROM "user" WHERE username = \'anderson\'')).fetchone()
        anderson_id = user_res[0]

    bind.execute(
        sa.text("UPDATE bookmark SET owner_id = :aid, is_active = true WHERE owner_id IS NULL"),
        {"aid": anderson_id}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_active')
        batch_op.drop_column('owner_id')

    op.drop_table('shared_bookmarks')
    # ### end Alembic commands ###
