"""remove finances

Revision ID: 961b6580d3f0
Revises: 5ee2bda1f6bc
Create Date: 2026-03-23 15:40:03.111474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961b6580d3f0'
down_revision = '5ee2bda1f6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('grupo', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
