"""add uuid to snippet

Revision ID: 9b5ad10b534e
Revises: fc644004893a
Create Date: 2026-04-15 10:35:21.766244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5ad10b534e'
down_revision = 'fc644004893a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    import uuid
    from sqlalchemy.sql import table, column
    from sqlalchemy import String

    # Add column as nullable first
    with op.batch_alter_table('snippet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
    
    # Populate existing rows with UUIDs
    snippet_table = table('snippet', column('id'), column('uuid'))
    conn = op.get_bind()
    for row in conn.execute(sa.select(snippet_table.c.id)).fetchall():
        id = row[0]
        new_uuid = str(uuid.uuid4())
        conn.execute(
            snippet_table.update().where(snippet_table.c.id == id).values(uuid=new_uuid)
        )

    # Now set it to NOT NULL and create constraint
    with op.batch_alter_table('snippet', schema=None) as batch_op:
        batch_op.alter_column('uuid', nullable=False)
        batch_op.create_unique_constraint('uq_snippet_uuid', ['uuid'])

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snippet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
