"""add_image_url_to_bookmark

Revision ID: 9be9a207b55e
Revises: a0e40402021c
Create Date: 2026-05-03 14:43:33.570482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be9a207b55e'
down_revision = 'a0e40402021c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
