"""Add perfumes table

Revision ID: 9f869d118482
Revises: 2890a0ba4d49
Create Date: 2026-04-13 13:57:23.452273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f869d118482'
down_revision = '2890a0ba4d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('correspondente', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfume')
    # ### end Alembic commands ###
