"""make_tipo_id_nullable

Revision ID: 9ff8bea07e86
Revises: 47a90a4cfccf
Create Date: 2026-05-03 13:41:18.162654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff8bea07e86'
down_revision = '47a90a4cfccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.alter_column('tipo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.alter_column('tipo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
