"""Add foto_url to Pessoa

Revision ID: fc644004893a
Revises: 4a39a0f7c3fb
Create Date: 2026-04-13 15:44:38.085306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc644004893a'
down_revision = '4a39a0f7c3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_column('foto_url')

    # ### end Alembic commands ###
